apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-stack-school
spec:
  replicas: 2
  selector:
    matchLabels:
      app: full-stack-school
  template:
    metadata:
      labels:
        app: full-stack-school
    spec:
      containers:
        - name: app
          image: duybo95/dashboard:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres:5432/fullstackschool
---
apiVersion: v1
kind: Service
metadata:
  name: full-stack-school-service
spec:
  type: LoadBalancer
  selector:
    app: full-stack-school
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
